[application]

name = "interspace"        # dioxus project name
default_platform = "web"    # default platfrom: web | desktop
out_dir = "dist"            # Web `build` & `serve` dist path
asset_dir = "res/static"    # resource (static) file folder

[application.tools]
binaryen = { wasm_opt = true }

[web.app]
title = "InterSpace"       # HTML title tag content


[web.watcher]
index_on_404 = true
watch_path = ["src", "./res/static"]


[web.resource]
style = ["./style/main.css", "./style/block.css", "./style/section.css", "./style/dynatable.css"]  # CSS files
script = ["./script/gridsizer.js"]                     # Javascript files


[web.resource.dev]
# Javascript code file
# serve: [dev-server] only
script = []


[application.plugins]
available = true
required = []
