

lang_section  = {"[" ~ INLINE_WHITE_SPACE ~ "lang" ~ INLINE_WHITE_SPACE ~ "]" ~ line_ends}


name = {"name" ~ padded_equals ~ string ~ line_ends}
website = {"website" ~ padded_equals ~ string ~ line_ends}
owner = {"owner" ~ padded_equals ~ ident ~ line_ends}
langtype = {"langtype" ~ padded_equals ~ "non-code" | "jit" | "aot" | "interpreted" ~ line_ends}


lang = {
    SOI ~
    WHITE_SPACE ~
    lang_section ~
    name ~
    website ~
    owner ~
    langtype ~
    WHITE_SPACE ~
    EOI
}
